#!/bin/bash

# main maker

if [[ ! -f __main__.py ]]; then
    ALLM=$(pwd | tr '/' '.' | tr -d '\n')

    # canonized module
    CM=""
    CMC=""
    ALL=()

    for M in $(echo -n $ALLM | tr '.' ' '); do
        ALL+=($M)
    done

    for ((i=${#ALL[@]}-1; i>=0; i--)); do
        CMC="../$CMC"
        A="${ALL[i]}"
        INI="$CMC$A/__init__.py"

        if [[ ! -f $INI ]]; then
            break
        fi

        if [[ -z $CM ]]; then
            CM="$A"
        else
            CM="$A.$CM"
        fi
        #echo "$A"
        #echo "$INI"
        #echo "$CM"
        #echo ""
    done



cat >__main__.py <<EOF
from $CM import main


if __name__ == "__main__":
    main()
EOF

fi
